/**
 * W3 scoring characterization — the BEHAVIORAL CONTRACT for the scoring
 * unification refactor. Every golden below is HAND-COMPUTED from the
 * documented formulas and constants (never generated by running the
 * implementation), so they lock intended behavior: the refactor must
 * reproduce them exactly, and any future weight tuning must consciously
 * edit them.
 *
 * Covered paths (the drift set):
 *   1. computeScore        — multiplicative recall ranking (search.ts:41)
 *   2. multiSignalScore    — additive surfacing score (search.ts:153)
 *   3. scoreRelevance      — hook-side tag relevance (utils/relevance.ts),
 *                            whose computeRecencyBoost is a byte-for-byte
 *                            duplicate of scoring.ts recencyBoost
 *   4. the parameter surface (weights/buckets) as constants
 *
 * Timestamps are constructed relative to now at MID-BUCKET offsets
 * (1d / 15d / 100d), so the bucketed recency values are stable regardless
 * of when the suite runs.
 */
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { computeScore, multiSignalScore, recencyBoost } from '../src/db/memory-repository/scoring.js';
import { scoreRelevance, isRelevant } from '../src/utils/relevance.js';
import { tokenOverlap } from '../src/utils/similarity.js';
import { SOURCE_WEIGHT, RELEVANCE, FINGERPRINT, SCORING_PROFILES } from '../src/constants/index.js';
import type { Memory } from '../src/db/memory-repository.js';

const daysAgo = (d: number): string => new Date(Date.now() - d * 86_400_000).toISOString();

function mkMemory(overrides: Partial<Memory>): Memory {
  return {
    id: 'char-mem',
    content: 'placeholder content',
    kind: 'fact',
    project: 'char-proj',
    tags: [],
    confidence: 0.5,
    source: 'learned',
    created_at: daysAgo(30),
    last_recalled: null,
    recall_count: 0,
    invalidated: false,
    expires_at: null,
    surface_count: 0,
    impact_count: 0,
    fingerprint: null,
    context: null,
    anchor: null,
    superseded_by: null,
    superseded_at: null,
    ...overrides,
  } as Memory;
}

const close = (actual: number, expected: number, label: string): void => {
  assert.ok(Math.abs(actual - expected) < 1e-12, `${label}: expected ${expected}, got ${actual}`);
};

describe('characterization — parameter surface (weights and buckets)', () => {
  it('locks the constants both formulas are built from', () => {
    assert.deepEqual({ ...SOURCE_WEIGHT }, { corrected: 1.5, user: 1.2, confirmed: 1.1, learned: 1.0 });
    assert.equal(RELEVANCE.RECENCY_BOOST_7_DAYS, 1.2);
    assert.equal(RELEVANCE.RECENCY_BOOST_30_DAYS, 1.0);
    assert.equal(RELEVANCE.RECENCY_BOOST_STALE, 0.8);
    assert.equal(RELEVANCE.INJECTION_THRESHOLD, 0.25);
    assert.deepEqual({ ...FINGERPRINT.WEIGHTS }, {
      FINGERPRINT: 0.20, VECTOR: 0.20, CONTENT: 0.20, CONFIDENCE: 0.15, RECENCY: 0.10, PRECISION: 0.15,
    });
    assert.deepEqual({ ...FINGERPRINT.DIMENSION_WEIGHTS }, { MODULE: 0.5, FRAMEWORK: 0.3, LANG: 0.2 });
    assert.equal(FINGERPRINT.LANG_MISMATCH_PENALTY, 0.5);
    assert.equal(FINGERPRINT.MIN_SCORE, 0.15);
  });

  it('locks the authoritative SCORING_PROFILES, including constant aliases by identity', () => {
    const { RECALL, SURFACING } = SCORING_PROFILES;
    assert.equal(RECALL.RELEVANCE_FLOOR, 0.3);
    assert.equal(RECALL.RELEVANCE_GAIN, 0.9);
    assert.equal(RECALL.SOURCE_WEIGHTS, SOURCE_WEIGHT, 'source weights alias the SAME object (decay also consumes it)');

    assert.equal(SURFACING.MULTI_SIGNAL.WEIGHTS, FINGERPRINT.WEIGHTS, 'signal weights alias the SAME object');
    assert.equal(SURFACING.MULTI_SIGNAL.LANG_MISMATCH_PENALTY, FINGERPRINT.LANG_MISMATCH_PENALTY);
    assert.equal(SURFACING.MULTI_SIGNAL.UNPROVEN_PRECISION_PROXY, 0.3);
    assert.equal(SURFACING.MULTI_SIGNAL.MIN_SCORE, FINGERPRINT.MIN_SCORE);

    assert.deepEqual({ ...SURFACING.TAG_RELEVANCE }, {
      EXTENSION_WEIGHT: 0.6, PATH_PART_WEIGHT: 0.3, COMMAND_WEIGHT: 0.2, MESSAGE_WEIGHT: 0.4,
      INJECTION_THRESHOLD: 0.25,
    });
    assert.equal(SURFACING.TAG_RELEVANCE.INJECTION_THRESHOLD, RELEVANCE.INJECTION_THRESHOLD);
  });
});

describe('characterization — recency buckets (shared primitive-to-be)', () => {
  it('1d → 1.2, 15d → 1.0, 100d → 0.8, never-recalled → 0.8', () => {
    assert.equal(recencyBoost(daysAgo(1)), 1.2);
    assert.equal(recencyBoost(daysAgo(15)), 1.0);
    assert.equal(recencyBoost(daysAgo(100)), 0.8);
    assert.equal(recencyBoost(null), 0.8);
  });
});

describe('characterization — tokenOverlap anchor cases', () => {
  it('identical → 1, disjoint → 0, one-of-three-union → 1/3', () => {
    assert.equal(tokenOverlap('alpha bravo charlie', 'alpha bravo charlie'), 1);
    assert.equal(tokenOverlap('alpha bravo', 'delta echo'), 0);
    // unigrams {alpha,bravo} vs {alpha,charlie}: ∩=1, ∪=3; bigrams disjoint → max(1/3, 0)
    close(tokenOverlap('alpha bravo', 'alpha charlie'), 1 / 3, 'partial overlap');
  });
});

describe('characterization — computeScore (multiplicative recall form)', () => {
  // conf × SOURCE_WEIGHT × recencyBoost × (0.3 + 0.9 × tokenOverlap)
  it('user source, fresh recall, identical content: 0.8×1.2×1.2×1.2', () => {
    const m = mkMemory({ confidence: 0.8, source: 'user', last_recalled: daysAgo(1), content: 'alpha bravo charlie' });
    close(computeScore(m, 'alpha bravo charlie'), 0.8 * 1.2 * 1.2 * 1.2, 'all-boost case');
  });

  it('learned source, never recalled, disjoint content: 0.5×1.0×0.8×0.3', () => {
    const m = mkMemory({ confidence: 0.5, source: 'learned', last_recalled: null, content: 'alpha bravo' });
    close(computeScore(m, 'delta echo'), 0.5 * 1.0 * 0.8 * 0.3, 'all-floor case');
  });

  it('corrected source, mid recency, one-third overlap: 0.6×1.5×1.0×(0.3+0.9/3)', () => {
    const m = mkMemory({ confidence: 0.6, source: 'corrected', last_recalled: daysAgo(15), content: 'alpha bravo' });
    close(computeScore(m, 'alpha charlie'), 0.6 * 1.5 * 1.0 * (0.3 + 0.9 * (1 / 3)), 'mid case');
  });

  it('confirmed source, stale recall, identical content: 0.9×1.1×0.8×1.2', () => {
    const m = mkMemory({ confidence: 0.9, source: 'confirmed', last_recalled: daysAgo(100), content: 'alpha bravo charlie' });
    close(computeScore(m, 'alpha bravo charlie'), 0.9 * 1.1 * 0.8 * 1.2, 'stale case');
  });
});

describe('characterization — multiSignalScore (additive surfacing form)', () => {
  const W = FINGERPRINT.WEIGHTS;

  it('all-signal maximum: fp 1, vector 0.7, content 1, conf 0.8, fresh, precision 5/10', () => {
    const m = mkMemory({
      confidence: 0.8,
      content: 'alpha bravo charlie',
      last_recalled: daysAgo(1),
      surface_count: 10,
      impact_count: 5,
      fingerprint: { lang: ['typescript'], framework: ['node'], module: ['api'] },
    });
    const queryFp = { lang: ['typescript'], framework: ['node'], module: ['api'] };
    const expected =
      W.FINGERPRINT * 1 + W.VECTOR * 0.7 + W.CONTENT * 1 + W.CONFIDENCE * 0.8 + W.RECENCY * 1 + W.PRECISION * 0.5;
    close(multiSignalScore(m, queryFp, 'alpha bravo charlie', 0.7), expected, 'all-max case');
  });

  it('bare memory: no fingerprint, no vector, disjoint content, never recalled, unproven precision proxy conf×0.3', () => {
    const m = mkMemory({ confidence: 0.6, content: 'alpha bravo', last_recalled: null, surface_count: 0, impact_count: 0 });
    const queryFp = { lang: ['typescript'], framework: [], module: [] };
    const expected = W.CONFIDENCE * 0.6 + W.PRECISION * (0.6 * 0.3);
    close(multiSignalScore(m, queryFp, 'delta echo', 0), expected, 'bare case (no lang penalty when memory has no fingerprint)');
  });

  it('lang mismatch halves the score when both sides carry disjoint langs', () => {
    const m = mkMemory({
      confidence: 0.7,
      content: 'alpha bravo',
      last_recalled: daysAgo(15),
      surface_count: 4,
      impact_count: 2,
      fingerprint: { lang: ['python'], framework: ['react'], module: ['auth'] },
    });
    const queryFp = { lang: ['typescript'], framework: ['react'], module: ['auth'] };
    // fp: module 1×0.5 + framework 1×0.3 + lang 0×0.2 = 0.8; recency 15d → (1.0−0.8)/(1.2−0.8) = 0.5
    const base =
      W.FINGERPRINT * 0.8 + W.CONTENT * (1 / 3) + W.CONFIDENCE * 0.7 + W.RECENCY * 0.5 + W.PRECISION * 0.5;
    close(multiSignalScore(m, queryFp, 'alpha charlie', 0), base * FINGERPRINT.LANG_MISMATCH_PENALTY, 'penalized case');
  });

  it('precision ratio caps at 1 when impacts exceed surfacings', () => {
    const m = mkMemory({ confidence: 0.5, content: 'alpha', last_recalled: null, surface_count: 2, impact_count: 6 });
    const queryFp = { lang: [], framework: [], module: [] };
    const expected = W.CONFIDENCE * 0.5 + W.PRECISION * 1;
    close(multiSignalScore(m, queryFp, 'unrelatedquery', 0), expected, 'capped precision');
  });
});

describe('characterization — scoreRelevance (hook-side tag path)', () => {
  it('extension + path-part tag matches, capped composition, duplicate recency buckets', () => {
    const m = mkMemory({ confidence: 0.5, tags: ['ts', 'api'], last_recalled: null });
    // 'ts' matches the extension (+0.6); 'api' matches a path part (+0.3) → 0.9
    const score = scoreRelevance(m, { filePath: 'src/api/auth.ts' });
    close(score, 0.9 * 0.5 * 0.8, 'tagMatch × confidence × recencyBoost');
    assert.equal(isRelevant(score), true, '0.36 > 0.25 injection threshold');
  });

  it('no tags → zero regardless of context', () => {
    const m = mkMemory({ confidence: 0.9, tags: [], last_recalled: daysAgo(1) });
    assert.equal(scoreRelevance(m, { filePath: 'src/api/auth.ts', userMessage: 'anything' }), 0);
  });

  it('tag-match components: command +0.2, message +0.4, capped at 1.0', () => {
    const m = mkMemory({ confidence: 1.0, tags: ['deploy'], last_recalled: daysAgo(1) });
    // command includes 'deploy' (+0.2) and message includes it (+0.4) → 0.6
    close(scoreRelevance(m, { command: 'npm run deploy', userMessage: 'please deploy now' }), 0.6 * 1.0 * 1.2, 'command+message');
  });

  it('injection threshold is a STRICT inequality: exactly 0.25 does not inject', () => {
    assert.equal(isRelevant(0.25), false, 'boundary value fails the strict > comparison');
    assert.equal(isRelevant(0.25 + 1e-9), true, 'anything above the threshold injects');
    assert.equal(isRelevant(0.2499), false);
  });
});
